---
title: '{"es"=>"Control Jets - Vuelos Privados", "en"=>"Control Jets - Private flights"}'
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: controljets@gmail.com
description:
  es: Renta un jet privado en México para cualquier ocasión. Vuelos nacionales e internacionales.
    Membresías desde 20 horas, carga aérea y más. ¡Cotiza ya!.
  en: Rent a private jet in Mexico for any ocassion. National and international flights.
    Memberships from 20 hours, air freight and more. Request a quote today!
index:
  es: 
  en: en/
baseurl: ''
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-sitemap
